language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- bower install
notifications:
  email: false
env:
  global:
    - secure: nrycymuC1gK4/gLqEoesLKUmN2du4uf7s6yakNv1aH00/w2DXCdpvPYGWMO0ztoGxK98dFcNYXlNMdQe1csZZkPnaVL1rDd/Pl0pSGRGJVwSfxgqpevWCidh66H1YDl2jbya0QvC0wiuWKXAdtp0OflxcWH8oFgbp6oKlAJ/of4=
    - secure: cmNLy33XN21xvf67G+AFJPMFE291nhGVV+SZS1HyS0/n0XYdIyKF46GItCoejqq+yLDh4l07YFXRWinRGLFYbF2mOKBFon+NWcnswRw61mvSIY01TnV0yhcwgc783Hybun0WKbnX3oh0Ru2WS2ef+t3+aUfZxtzVYUMU8utxRuw=
