language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- bower install
notifications:
  email: false
env:
  global:
  - secure: Oj/qDqzPd1who49IyMVD/y9i1XWPWhzca1GYONVOnICH3kNsyZPWlap+OV8sZGfYuoMeBQMH7w9GwdA+vad5xwOIisRAWINiLFD3XjwyDZiGIRmghgUq3izNr2kW0JnL/AFlInpvOGNuMgGbBLqJzLqHSlHtGpMQ99f4ucUHdYc=
  - secure: I2d2kTC6aew7lISrYvYj+8hG1zlBWjBYN6ghvCA1ynt/DKRhfhfoe48f79ZZw/4h9aDJ2TPjpHuWkVuR+mAlUsiXggd6g2jskoMPozUjVWM4acpX8B/ocNpP8nQRPi6XOh5a3ijQajeV/wyQK4FlYmGOX8k6UpL09VeTBtxNdGI=
