language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- bower install
notifications:
  email: false
env:
  global:
    - secure: P/NHlxAbEMJPsfEm/7CZz0pr/tdnekIo4lDgx2UhU9zOvnIXlu40Y/ZUtRCQHsikbhRRG6Y1sjOmBfXjQu9EG2p3wiKXGozsrhJg8f5+UzjVzFy6O4xG5KWDwSxjayS4XDpC7ngLzuUv8B+gjwaSMy0qIcZx78h/YSQb0LXe6Aw=
    - secure: CB16cEm+sDNbBdy7DY8hCHZYHmYoN4aHxS/LW0JvQxoC742IIZmAdwpPZONNlsv8g29kXjyftZk+XHZEgjLnt4Bbe1OCUny2GahcAWgan+KxIBH9FcOLVJ568SEwYkXjpTFoetvcsnAHUl5qy7ouUI6T/b/sjUA4Sqs6t2A3EBo=
