language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- bower install
notifications:
  email: false
env:
  global:
    - secure: ZpWulmqkrpbVmWgvt240/erLMHpFp92plPvlAfp2B2X/s/SG5g9qxEOTgarHa/5xr4tvX7Ic6/MwpZU89fpjD+beMPw5iGXgGq2fwlWQu6n05R4mxVSloIIut3EPYtaoplQ73lfiJow1TEybJukTg47T9KRsS7UJShirrlZjsQ8=
    - secure: A8EMP38Ndj+J9LdkmROZ/zaLLSeEFatnzaWJOKogOt0MAGG6IuQxXBWEm3lIfrfI3xzUrkgU1LVH31M2CNlIrQONITG4iQweBnUNiCNnuTLZhruFtUibnjcIZErXVVOWc2AmqFKbnyTxwCiR5XEDD5fesaJA2PuWUZ3RygMMGeU=
