language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- bower install
notifications:
  email: false
env:
  global:
    - secure: dQRuoaST94BB9JLb7BjSvnN0fnxF5QidMLLXdwntAq9kx/Upl3FarJ+MCVKEfBNWfMnPdW/wyGq/SnzFwgAAQZ9/3BeVSwv2M/WEBJTO/vdbXP0rbsuw0jhuQcD1X6flim7rDPkzfoZ9EbDC2A8sNHCcj+4jSD3POyUsaHpU6/E=
    - secure: WyWljlBmwnIiWdAERY6lvujw5iJRceT8gWYe2sa193TFtL8yCcy0tGDZQf9AgdE7xEykCEuYOz9WOEyxn051TuyeDoSAFoV9Z+AW3IhcHSDGBA5JhClncTHSZFKkvdNYogNp4cHPro7Iq9zNCMOeBFXmU69+b6sF6QsTISe8tsc=
